### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by louy2** [elm-lang/elm-lang.org#636] opened 2016-09-19 01:04 UTC
Make all related servers support HTTPS.

Ref: 
- https://letsencrypt.org/
- https://hackage.haskell.org/package/warp-tls
- https://github.com/noteed/acme

SSCCE: https://elm-lang.org

**Comment by evancz** [comment] 2016-09-19 23:56
Duplicate of #624

**Closed by evancz** 2016-09-19 23:56 UTC
