### ISSUE TITLE
Signal -> Input link 404s

### ISSUE THREAD

**Issue by tomjaguarpaw** [elm-lang/elm-lang.org#237] opened 2015-01-12 20:35 UTC
This page

http://elm-lang.org/learn/Interactive-UI-Elements.elm

linked from here

http://elm-lang.org/Learn.elm

gives me a 404.

**Comment by sebastiant** [comment] 2015-01-16 16:50
Duplicate of #230

**Comment by evancz** [comment] 2015-02-14 14:25
That link has been removed in favor of https://github.com/evancz/elm-architecture-tutorial, check that out instead!

**Closed by evancz** 2015-02-14 14:25 UTC
