### ISSUE TITLE
Hot Swap doesn't work

### ISSUE THREAD

**Issue by lepinay** [elm-lang/elm-lang.org#226] opened 2014-12-30 10:36 UTC
This feature doesn't work anymore on the live site.

**Comment by stefanodacchille** [comment] 2015-02-15 13:09
Any updates on this? I think it's such a pity this is broken since it's one of the coolest features of the language

**Comment by evancz** [comment] 2015-06-12 01:32
I believe this is a duplicate of #176 which has a nice example that makes it easy to reproduce. Let's follow along there.

**Closed by evancz** 2015-06-12 01:32 UTC
