### ISSUE TITLE
elm-lang.org examples has broken links

### ISSUE THREAD

**Issue by RichardWright** [elm-lang/elm-lang.org#633] opened 2016-09-15 14:58 UTC
http://elm-lang.org/examples/markdown for example returns 

A web handler threw an exception. Details:
gen/pages/404.html: getFileStatus: does not exist (No such file or directory)

**Comment by evancz** [comment] 2016-09-20 00:19
Duplicate of https://github.com/elm-lang/elm-lang.org/issues/607

**Closed by evancz** 2016-09-20 00:19 UTC
