### ISSUE TITLE
Typechecker can't weaken `comparable` to `number` without explicit constraints

### ISSUE THREAD

**Issue by JoeyEremondi** [elm-lang/elm-lang.org#539] opened 2016-03-01 22:40 UTC
A minimal example, based on [this thread](https://mail.google.com/mail/u/0/#inbox/1533417b93929fd3)
Consider the following code:

```elm
badMaxNumber : List number -> Maybe number
badMaxNumber l =
  case l of
    [] ->
      Nothing

    h :: t ->
      Just <| List.foldl max h t

goodMaxNumber : List number -> Maybe number
goodMaxNumber l =
  case l of
    [] ->
      Nothing

    h :: t ->
      Just <| List.foldl max (h+0) t
```
The first function fails with a mismatch between `List number -> Maybe number` and `List comparable -> Maybe comparable`.

The second function typechecks just fine, since the (+0) constraint tells it that we're looking at numbers, not comparables.

Should the typechecker be able to tell that `number` is a subtype of `comparable`, just like it knows `Int` is a subtype of `number`? Or is the price of having hacky (+0)s throughout the code worth the simplicity of avoiding a type heirarchy?

**Comment by jvoigtlaender** [comment] 2016-03-01 22:50
Why report this here? Isn't that the wrong repo? And in any case, the issue looks just a duplicate of https://github.com/elm-lang/elm-compiler/issues/1281.

**Comment by JoeyEremondi** [comment] 2016-03-01 22:51
Bah, definitely the wrong repo, and I wasn't familiar with the previous issue, probably because I was looking in the wrong repo. Sorry!.

**Closed** 2016-03-01 22:51 UTC
