### ISSUE TITLE
The 'use fewer parens' in examples section gives 404

### ISSUE THREAD

**Issue by jhrcek** [elm-lang/elm-lang.org#602] opened 2016-06-30 21:12 UTC
This page http://elm-lang.org/examples links to 'use fewer parens' page here http://elm-lang.org/examples/forward-apply  but navigating there returns http 404 error

**Comment by evancz** [comment] 2016-06-30 22:15
Duplicate of #577

**Closed by evancz** 2016-06-30 22:15 UTC
